/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        "surface":                   "#fdf9f0",
        "surface-bright":            "#fdf9f0",
        "surface-dim":               "#dedad1",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f8f3ea",
        "surface-container":         "#f2ede4",
        "surface-container-high":    "#ece8df",
        "surface-container-highest": "#e6e2d9",
        "on-surface":                "#1d1c16",
        "on-surface-variant":        "#4f4632",
        "primary":                   "#765a00",
        "primary-container":         "#ffc600",
        "on-primary":                "#ffffff",
        "on-primary-container":      "#6e5400",
        "primary-fixed":             "#ffdf96",
        "primary-fixed-dim":         "#f6bf00",
        "on-primary-fixed":          "#251a00",
        "on-primary-fixed-variant":  "#594400",
        "secondary":                 "#546159",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#d5e3d9",
        "on-secondary-container":    "#58665d",
        "secondary-fixed":           "#d8e6db",
        "secondary-fixed-dim":       "#bccac0",
        "tertiary":                  "#5f5e5e",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#cfcdcd",
        "on-tertiary-container":     "#585757",
        "tertiary-fixed":            "#e4e2e1",
        "tertiary-fixed-dim":        "#c8c6c6",
        "on-tertiary-fixed":         "#1b1c1c",
        "on-tertiary-fixed-variant": "#474747",
        "outline":                   "#81765f",
        "outline-variant":           "#d3c5ab",
        "inverse-surface":           "#32302a",
        "inverse-on-surface":        "#f5f0e7",
        "inverse-primary":           "#f6bf00",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
        "background":                "#fdf9f0",
        "on-background":             "#1d1c16",
        "surface-tint":              "#765a00",
        "surface-variant":           "#e6e2d9",
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body:     ['Work Sans', 'sans-serif'],
        label:    ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:   '0.125rem',
        md:   '0.375rem',
        lg:   '0.5rem',
        xl:   '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
